{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## OCT Playground\n",
    "Sandbox to play around with the different OCT Deep Learning Applications"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Fri Oct 15 18:14:29 2021       \n",
      "+-----------------------------------------------------------------------------+\n",
      "| NVIDIA-SMI 455.45.01    Driver Version: 455.45.01    CUDA Version: 11.1     |\n",
      "|-------------------------------+----------------------+----------------------+\n",
      "| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |\n",
      "| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |\n",
      "|                               |                      |               MIG M. |\n",
      "|===============================+======================+======================|\n",
      "|   0  Quadro RTX 8000     Off  | 00000000:15:00.0 Off |                  Off |\n",
      "| 33%   27C    P8     7W / 260W |      0MiB / 48601MiB |      0%      Default |\n",
      "|                               |                      |                  N/A |\n",
      "+-------------------------------+----------------------+----------------------+\n",
      "                                                                               \n",
      "+-----------------------------------------------------------------------------+\n",
      "| Processes:                                                                  |\n",
      "|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |\n",
      "|        ID   ID                                                   Usage      |\n",
      "|=============================================================================|\n",
      "|  No running processes found                                                 |\n",
      "+-----------------------------------------------------------------------------+\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[34m\u001b[1mwandb\u001b[0m: Currently logged in as: \u001b[33msgvdan\u001b[0m (use `wandb login --relogin` to force relogin)\n"
     ]
    }
   ],
   "source": [
    "### Init\n",
    "\n",
    "# Show Resources\n",
    "!nvidia-smi\n",
    "\n",
    "# Auto reload\n",
    "%load_ext autoreload\n",
    "%autoreload 2\n",
    "\n",
    "# Imports\n",
    "import wandb\n",
    "wandb.login()\n",
    "from experiment import Experiment"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[autoreload of graphql.language.ast failed: Traceback (most recent call last):\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 317, in update_class\n",
      "    update_instances(old, new)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 280, in update_instances\n",
      "    ref.__class__ = new\n",
      "TypeError: __class__ assignment: 'Document' object layout differs from 'Document'\n",
      "]\n",
      "[autoreload of graphql.type.definition failed: Traceback (most recent call last):\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 317, in update_class\n",
      "    update_instances(old, new)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 280, in update_instances\n",
      "    ref.__class__ = new\n",
      "TypeError: __class__ assignment: 'GraphQLScalarType' object layout differs from 'GraphQLScalarType'\n",
      "]\n",
      "[autoreload of graphql failed: Traceback (most recent call last):\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/graphql/__init__.py\", line 46, in <module>\n",
      "    from .graphql import graphql, graphql_sync\n",
      "ImportError: cannot import name 'graphql_sync' from 'graphql.graphql' (/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/wandb/vendor/graphql-core-1.1/graphql/graphql.py)\n",
      "]\n",
      "[autoreload of wandb.apis.public failed: Traceback (most recent call last):\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 292, in update_class\n",
      "    if (old_obj == new_obj) is True:\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/wandb/vendor/graphql-core-1.1/graphql/language/ast.py\", line 26, in __eq__\n",
      "    self.definitions == other.definitions\n",
      "TypeError: descriptor 'definitions' for 'Document' objects doesn't apply to a 'Document' object\n",
      "]\n",
      "[autoreload of wandb.sdk.wandb_config failed: Traceback (most recent call last):\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 317, in update_class\n",
      "    update_instances(old, new)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 280, in update_instances\n",
      "    ref.__class__ = new\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/wandb/sdk/wandb_config.py\", line 139, in __setitem__\n",
      "    with wandb.wandb_lib.telemetry.context() as tel:\n",
      "AttributeError: module 'wandb.sdk.lib' has no attribute 'telemetry'\n",
      "]\n",
      "[autoreload of wandb.sdk.wandb_settings failed: Traceback (most recent call last):\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 317, in update_class\n",
      "    update_instances(old, new)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 280, in update_instances\n",
      "    ref.__class__ = new\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py\", line 1021, in __setattr__\n",
      "    self._update({name: value}, _source=self.Source.SETUP)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py\", line 863, in _update\n",
      "    raise TypeError(\"Settings object is frozen\")\n",
      "TypeError: Settings object is frozen\n",
      "]\n",
      "[autoreload of wandb.proto.wandb_telemetry_pb2 failed: Traceback (most recent call last):\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/wandb/proto/wandb_telemetry_pb2.py\", line 16, in <module>\n",
      "    DESCRIPTOR = _descriptor.FileDescriptor(\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/google/protobuf/descriptor.py\", line 942, in __new__\n",
      "    return _message.default_pool.AddSerializedFile(serialized_pb)\n",
      "TypeError: Couldn't build proto file into descriptor pool!\n",
      "Invalid proto descriptor for file \"wandb/proto/wandb_telemetry.proto\":\n",
      "  wandb/proto/wandb_telemetry.proto: A file with this name is already in the pool.\n",
      "\n",
      "]\n",
      "[autoreload of wandb.sdk.wandb_summary failed: Traceback (most recent call last):\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 317, in update_class\n",
      "    update_instances(old, new)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 280, in update_instances\n",
      "    ref.__class__ = new\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/wandb/sdk/wandb_summary.py\", line 54, in __setitem__\n",
      "    self.update({key: val})\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/wandb/sdk/wandb_summary.py\", line 76, in update\n",
      "    self._update(record)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/wandb/sdk/wandb_summary.py\", line 131, in _update\n",
      "    self._update_callback(record)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 857, in _summary_update_callback\n",
      "    def to_html(self, height: int = 420, hidden: bool = False) -> str:\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/wandb/sdk/interface/interface.py\", line 625, in publish_summary\n",
      "    self._publish_summary(pb_summary_record)\n",
      "Exception: The wandb backend process has shutdown\n",
      "]\n",
      "[autoreload of wandb.sdk.wandb_run failed: Traceback (most recent call last):\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 317, in update_class\n",
      "    update_instances(old, new)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 280, in update_instances\n",
      "    ref.__class__ = new\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 419, in __setattr__\n",
      "    super(Run, self).__setattr__(attr, value)\n",
      "TypeError: super(type, obj): obj must be an instance or subtype of type\n",
      "]\n",
      "[autoreload of watchdog.utils.bricks failed: Traceback (most recent call last):\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: _init() requires a code object with 0 free vars, not 1\n",
      "]\n",
      "[autoreload of watchdog.events failed: Traceback (most recent call last):\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: dispatch() requires a code object with 0 free vars, not 1\n",
      "]\n",
      "[autoreload of wandb failed: Traceback (most recent call last):\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/labs/waic/sgvdan/.conda/envs/segev-workspace/lib/python3.8/site-packages/wandb/__init__.py\", line 38, in <module>\n",
      "    wandb.wandb_lib = wandb_sdk.lib\n",
      "AttributeError: module 'wandb.sdk' has no attribute 'lib'\n",
      "]\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Currently logged in as: \u001b[33msgvdan\u001b[0m (use `wandb login --relogin` to force relogin)\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: wandb version 0.12.4 is available!  To upgrade, please run:\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m:  $ pip install wandb --upgrade\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "\n",
       "                    Syncing run <strong><a href=\"https://wandb.ai/sgvdan/OCT-DL/runs/1bcs9c4d\" target=\"_blank\">driven-thunder-128</a></strong> to <a href=\"https://wandb.ai/sgvdan/OCT-DL\" target=\"_blank\">Weights & Biases</a> (<a href=\"https://docs.wandb.com/integrations/jupyter.html\" target=\"_blank\">docs</a>).<br/>\n",
       "\n",
       "                "
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Load Train\n",
      "Load Validation\n",
      "Load Test\n",
      "loading vgg19_nominal model...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  0%|          | 0/7 [00:00<?, ?it/s]"
     ]
    }
   ],
   "source": [
    "### Parameters\n",
    "default_config = {'dataset_control_path': 'Data/train/control',\n",
    "                  'dataset_study_path': 'Data/train/study',\n",
    "                  \n",
    "                  'test_size': 0.2, 'validation_size': 0.15, 'training_size': 0.65,\n",
    "                  'cache_path': './.cache-full',\n",
    "                  'refresh_cache': False,\n",
    "                  \n",
    "                  'input_size': (496, 1024), # Some samples are (496, 512)\n",
    "                  'model_name': 'vgg19_nominal',\n",
    "                  'epochs': 7,\n",
    "                  'lr': 1e-4,\n",
    "                  'batch_size': 50,\n",
    "\n",
    "                  'device': 'cuda',\n",
    "                  }\n",
    "\n",
    "### Subroutines\n",
    "def agent():\n",
    "    with wandb.init(project=\"OCT-DL\", config=default_config):\n",
    "        config = wandb.config\n",
    "        experiment = Experiment(config)\n",
    "        experiment.run()\n",
    "\n",
    "### Playground\n",
    "agent()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
